apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "chris-ebpf-demo"
  region: "us-west-1"
  version: "1.20"

#availabilityZones: ["", "", ""]

managedNodeGroups:
- name: "ng-m5-large"
  ami: "ami-0fbc2c25239bc632c"
  desiredCapacity: 2
  # choose proper size for worker node instance as the node size detemines the number of pods that a node can run
  # it's limited by a max number of interfeces and private IPs per interface
  # t3.large has max 3 interfaces and allows up to 12 IPs per interface, therefore can run up to 36 pods per node
  # see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI
  instanceType: "m5.large"
  ssh:
    # uncomment lines below to allow SSH access to the nodes using existing EC2 key pair
    publicKeyName: chris-aws-uw2-keypair
    allow: true
  overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh chris-ebpf-demo
# enable all of the control plane logs:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
