apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "$CLUSTER_NAME"
  region: "$AWS_REGION"
  version: "1.21"

#availabilityZones: ["", "", ""]

managedNodeGroups:
- name: "ng-m5-large"
  ami: "ami-006df5a9e91a213e3"
  desiredCapacity: 2
  # choose proper size for worker node instance as the node size detemines the number of pods that a node can run
  # it's limited by a max number of interfeces and private IPs per interface
  # m5.large has max 3 interfaces and allows up to 10 IPs per interface, therefore can run up to 30 pods per node
  # see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI
  instanceType: "m5.large"
  ssh:
    # uncomment lines below to allow SSH access to the nodes using existing EC2 key pair
    publicKeyName: $KEYPAIR_NAME
    allow: true
  overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh $CLUSTER_NAME
# enable all of the control plane logs:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]